/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "isr_uart_rx.h"
#include "Clock_PWM_A.h"
#include "IN3_aliases.h"
#include "IN3.h"
#include "Clock_PWM_B.h"
#include "PWM_B.h"
#include "IN4_aliases.h"
#include "IN4.h"
#include "PWM_A.h"
#include "IN2_aliases.h"
#include "IN2.h"
#include "IN1_aliases.h"
#include "IN1.h"
#include "UART_BT.h"
#include "isr_uart_rx_BT.h"
#include "UART_IntClock.h"
#include "UART_BT_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

